default:
    @just --list

read_lines:
    nu ./scripts.nu run listing_141_load_store_ports load 100_000_000

read_simd_throughput:
    nu ./scripts.nu run-precise default,precise_rep_test listing_142_simd load_width 100_000_000

read_simd_lines:
    nu ./scripts.nu run-precise listing_142_simd load_lines 100_000_000

write_simd_lines:
    nu ./scripts.nu run-precise listing_142_simd write_lines 100_000_000

cache_size:
    nu ./scripts.nu run-precise listing_143_cache_size

cache_size_non_bin:
    nu ./scripts.nu run-precise listing_144_non_power_of_two info

cache_size_non_bin_csv:
    nu ./scripts.nu run-precise listing_144_non_power_of_two csv > ./cache.csv

aligned_vs_unaligned_synt:
    nu ./scripts.nu run-precise listing_145_aligned_vs_unaligned 100_000_000 synthetic csv > aligned_vs_unaligned_synt.csv

aligned_vs_unaligned_l2:
    nu ./scripts.nu run-precise listing_145_aligned_vs_unaligned 262_144 real csv > aligned_vs_unaligned_l2.csv

aligned_vs_unaligned_l3:
    nu ./scripts.nu run-precise listing_145_aligned_vs_unaligned 1_048_576 real csv > aligned_vs_unaligned_l3.csv

aligned_vs_unaligned_main:
    nu ./scripts.nu run-precise listing_145_aligned_vs_unaligned 128_777_216 real print

nuke_l1:
    nu ./scripts.nu run-precise listing_146_nuke_cache 1_048_576

non_temporal:
    nu ./scripts.nu run-precise listing_147_non_temporal_store

prefetching:
    nu ./scripts.nu run-precise listing_148_prefetching
